DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS SERVICO;
DROP TABLE IF EXISTS CLIENTE_OFERTA_SERVICO;

CREATE TABLE CLIENTE(
	CPF INTEGER NOT NULL,
    DATA_NASCIMENTO DATE,
    EMAIL VARCHAR(200),
    NOME VARCHAR(100),
	GENERO INTEGER,
    SENHA VARCHAR(100),
    TELEFONE VARCHAR(20),
    
    PRIMARY KEY(CPF)
);

CREATE TABLE SERVICO(
	ID INTEGER NOT NULL,
    NOME_SERVICO VARCHAR(200),
    CIDADE VARCHAR(30),
    ESTADO VARCHAR(30),
    DESCRICAO VARCHAR(244),
	
    
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE_OFERTA_SERVICO (
	CLIENTE_CPF INTEGER NOT NULL,
    CLIENTE_NOME VARCHAR(100),
    SERVICO_ID INTEGER NOT NULL,
    SERVICO VARCHAR(200),
    
    PRIMARY KEY (CLIENTE_CPF),
    FOREIGN KEY (CLIENTE_CPF) REFERENCES CLIENTE(CPF),
    FOREIGN KEY (CLIENTE_NOME) REFERENCES CLIENTE(NOME),
	FOREIGN KEY (SERVICO_ID) REFERENCES SERVICO(ID),
    FOREIGN KEY (SERVICO) REFERENCES SERVICO(SERVICO)

)