DROP TABLE IF EXISTS CLIENTE_OFERTA_SERVICO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS SERVICO;


CREATE TABLE CLIENTE(
//	CPF varchar(20),
    DATA_NASCIMENTO DATE,
    EMAIL VARCHAR(200),
    NOME VARCHAR(100),
    SENHA VARCHAR(100),
    TELEFONE VARCHAR(20),
    
    PRIMARY KEY(CPF)
);

CREATE TABLE SERVICO(
	ID INTEGER NOT NULL,
    NOME_SERVICO VARCHAR(200),
    CIDADE VARCHAR(30),
    ESTADO VARCHAR(30),
    DESCRICAO VARCHAR(244),
	
    
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE_OFERTA_SERVICO(
	CPF_CLIENTE VARCHAR(20),
    ID_SERVICO INTEGER NOT NULL,
    
    PRIMARY KEY(CPF_CLIENTE,ID_SERVICO),
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF),
    FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO(ID)

);
